### ISSUE TITLE
Lacking content :P

### ISSUE THREAD

**Issue by danielpaul** [LevinGeorge/Jesus-Youth-Website#1]

**Comment by danielpaul** [comment]
No updates and pushes on this repo yet?

**Comment by LevinGeorge** [comment]
Not yet

**Comment by danielpaul** [comment]
You do know that we need to submit it again tomorrow rite?

**Comment by LevinGeorge** [comment]
Nope
We dont?! do we?? :O I thought it was just duplicating his code

**Comment by danielpaul** [comment]
Ohh oops. My bad :P
